name: ios-tipkit-20260227-131944-e85f4f
options:
  minimumXcodeGenVersion: 2.38.0
  deploymentTarget:
    iOS: 17.0
settings:
  base:
    PRODUCT_BUNDLE_IDENTIFIER: com.ryankaya.ios-tipkit-20260227-131944-e85f4f
    SWIFT_VERSION: 5.0
targets:
  ios-tipkit-20260227-131944-e85f4f:
    type: application
    platform: iOS
    sources:
      - path: Sources
    settings:
      base:
        INFOPLIST_FILE: Sources/ios-tipkit-20260227-131944-e85f4f/Info.plist
        PRODUCT_NAME: ios-tipkit-20260227-131944-e85f4f
        TARGETED_DEVICE_FAMILY: 1,2
        CODE_SIGN_STYLE: Automatic
        CURRENT_PROJECT_VERSION: 1
        MARKETING_VERSION: 1.0
    info:
      path: Sources/ios-tipkit-20260227-131944-e85f4f/Info.plist
      properties:
        UILaunchScreen: {}
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
    scheme:
      testTargets: []
